project_id = "aoxzoymzaorwwnrgjbrw"

[functions.generate-quiz]
verify_jwt = true

[functions.generate-mock-questions]
verify_jwt = false

[functions.check-quiz-answer]
verify_jwt = false

[functions.update-quiz-session]
verify_jwt = false

[functions.submit-mock-test]
verify_jwt = false
